"""
Fleet table: game stats for each vessel. Models live in ships_models.py.

Real-world figures (passengers, vehicles, service speed, years) are
approximate and rounded; see README.md.
"""
import os as _os
import sys as _sys
_sys.path.insert(0, _os.path.join(_os.path.dirname(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))), "common"))

from ships_models import *  # noqa: F401,F403

# ---------------------------------------------------------------------------
# Fleet table
#   pax / cars: real capacities (approx.)   kn: service speed in knots
#   cost / run: OpenTTD cost_factor / running_cost_factor
# ---------------------------------------------------------------------------
FLEET = [
    dict(id="coho", weather=0.45, name="MV Coho", model=m_coho, year=1959, pax=1000, cars=115, kn=15,
         cost=150, run=120, life=50, model_life=90,
         desc="Black Ball Ferry Line, Port Angeles - Victoria, in its current white and red livery. Still in service."),
    dict(id="sidney", weather=0.4, name="Sidney class", model=m_sidney, year=1960, pax=1000, cars=106, kn=18,
         cost=140, run=120, life=40, model_life=25,
         desc="The original BC Ferries pair (Sidney / Tsawwassen). Double-ended."),
    dict(id="vclass", weather=0.4, name="V-class", model=m_vclass, year=1962, pax=1000, cars=106, kn=18,
         cost=145, run=120, life=40, model_life=10,
         desc="Queen of Victoria, Queen of Vancouver and sisters, as built."),
    dict(id="vclass_s", weather=0.55, name="V-class (stretched)", model=lambda: m_vclass(True), year=1970,
         pax=1360, cars=192, kn=18, cost=165, run=130, life=40, model_life=30,
         variant_of="vclass",
         desc="V-class after the 1970s stretching and raising."),
    dict(id="burnaby", weather=0.65, name="Burnaby class", model=m_burnaby, year=1965, pax=1200, cars=192, kn=18,
         cost=160, run=130, life=45, model_life=25,
         desc="Queen of Burnaby, Queen of Nanaimo, Queen of New Westminster."),
    dict(id="bowen", weather=0.6, name="Bowen class", model=m_bowen, year=1965, pax=400, cars=70, kn=14,
         cost=90, run=70, life=55, model_life=40,
         desc="Bowen Queen, Mayne Queen and Powell River Queen. Inter-island workhorses."),
    dict(id="rupert", weather=0.55, name="Queen of Prince Rupert", model=m_prince_rupert, year=1966,
         pax=458, cars=80, kn=18, cost=130, run=110, life=45, model_life=30,
         desc="Northern route vessel, Prince Rupert - Haida Gwaii."),
    dict(id="tclass", weather=0.6, name="T-class", model=m_tclass, year=1969, pax=150, cars=26, kn=11,
         cost=50, run=40, life=55, model_life=40,
         desc="Tachek and Quadra Queen II. Small side-cabin minor route ferries."),
    dict(id="nimpkish", weather=0.55, name="Nimpkish", model=m_nimpkish, year=1973, pax=95, cars=16, kn=10,
         cost=40, run=32, life=50, model_life=40,
         desc="Small single-ended ferry for isolated coastal runs."),
    dict(id="cclass", weather=0.6, name="C-class", model=m_cclass, year=1976, pax=1466, cars=362, kn=20.5,
         cost=190, run=150, life=50, model_life=10,
         desc="Queen of Coquitlam, Queen of Cowichan, Queen of Alberni."),
    dict(id="cclass_ob", weather=0.65, name="C-class (Oak Bay)", model=lambda: m_cclass(True), year=1981,
         pax=1494, cars=322, kn=20.5, cost=190, run=150, life=50, model_life=45,
         variant_of="cclass",
         desc="Queen of Oak Bay and Queen of Surrey."),
    dict(id="quinitsa", weather=0.6, name="Quinitsa", model=m_quinitsa, year=1977, pax=300, cars=44, kn=12,
         cost=65, run=50, life=50, model_life=35,
         desc="Minor route ferry with a side-mounted cabin."),
    dict(id="north", weather=0.4, name="Queen of the North", model=m_north, year=1980, pax=700, cars=115, kn=19,
         cost=150, run=125, life=40, model_life=26,
         desc="Inside Passage ferry, Port Hardy - Prince Rupert."),
    dict(id="quinsam", weather=0.55, name="Quinsam", model=m_quinsam, year=1982, pax=400, cars=63, kn=11.5,
         cost=80, run=60, life=50, model_life=40,
         desc="Inter-island ferry with side cabin and open car deck."),
    dict(id="intermediate", weather=0.5, name="Intermediate class", model=m_intermediate, year=1991,
         pax=462, cars=100, kn=15.5, cost=110, run=80, life=45, model_life=35,
         desc="Queen of Capilano and Queen of Cumberland."),
    dict(id="spirit", weather=0.35, name="Spirit class", model=m_spirit, year=1993, pax=2100, cars=358, kn=19.5,
         cost=230, run=170, life=50, model_life=25,
         desc="Spirit of British Columbia and Spirit of Vancouver Island. The largest in the fleet."),
    dict(id="spirit_lng", weather=0.25, name="Spirit class (LNG)", model=lambda: m_spirit(True), year=2018,
         pax=1965, cars=358, kn=19.5, cost=235, run=130, life=40, model_life=30,
         variant_of="spirit",
         desc="Spirit class after the 2018 dual-fuel LNG mid-life upgrade. Cheaper to run."),
    dict(id="century", weather=0.4, name="Century class", model=m_century, year=1997, pax=600, cars=92, kn=14.5,
         cost=105, run=80, life=45, model_life=30,
         desc="Skeena Queen, the only one built. Open car deck under a passenger arch."),
    dict(id="pacificat", weather=0.1, name="PacifiCat class", model=m_pacificat, year=1999, pax=1000, cars=250,
         kn=34, cost=250, run=250, life=20, model_life=5,
         desc="The infamous aluminium fast-cat. Very fast, very expensive to run."),
    dict(id="nadventure", weather=0.35, name="Northern Adventure", model=m_northern_adventure, year=2007,
         pax=600, cars=112, kn=19, cost=150, run=115, life=40, model_life=30,
         desc="Northern route vessel serving Prince Rupert and Haida Gwaii."),
    dict(id="coastal", weather=0.25, name="Coastal class", model=m_coastal, year=2008, pax=1604, cars=310, kn=21,
         cost=220, run=150, life=50, model_life=40,
         desc="Coastal Renaissance, Coastal Inspiration and Coastal Celebration."),
    dict(id="coastal_2010", weather=0.12, name="Coastal class (Vancouver 2010)", model=lambda: m_coastal(True),
         year=2008, pax=1604, cars=310, kn=21, cost=220, run=150, life=50, model_life=40,
         variant_of="coastal",
         desc="The Coastal class as delivered, wrapped in the Vancouver 2010 Winter Olympics livery."),
    dict(id="nexpedition", weather=0.25, name="Northern Expedition", model=m_northern_expedition, year=2009,
         pax=600, cars=130, kn=19.5, cost=175, run=130, life=45, model_life=35,
         desc="Inside Passage cruise ferry with overnight cabins."),
    dict(id="salish", weather=0.15, name="Salish class", model=m_salish, year=2016, pax=600, cars=145, kn=15.5,
         cost=150, run=90, life=45, model_life=40,
         desc="Salish Orca, dual-fuel LNG. Hull art by Coast Salish artist Darlene Gait "
              "(Esquimalt Nation)."),
    dict(id="island", weather=0.08, name="Island class", model=m_island, year=2020, pax=300, cars=47, kn=14,
         cost=110, run=45, life=45, model_life=60,
         desc="Battery-electric-ready hybrid minor route ferries."),
    dict(id="piratepak", weather=0.0, name="Pirate Pak", model=m_piratepak, year=1970, pax=4, cars=1, kn=6,
         cost=12, run=6, life=3, model_life=120, joke=True,
         desc="A White Spot Pirate Pak, set afloat. Crew of four small pirates, one burger, "
              "one drink, one ice cream. Cardboard hull: replace often. Arrr!"),

    # ---- sister ships: appended so existing engine IDs never change --------
    dict(id="spirit_vi", weather=0.35, name="Spirit of Vancouver Island",
         model=lambda: m_spirit(key="spirit_vi"), year=1994, pax=2100, cars=358, kn=19.5,
         cost=230, run=170, life=50, model_life=25, variant_of="spirit",
         desc="Second of the Spirit class, sister to Spirit of British Columbia."),
    dict(id="coastal_insp", weather=0.25, name="Coastal Inspiration",
         model=lambda: m_coastal(key="coastal_insp"), year=2008, pax=1604, cars=310, kn=21,
         cost=220, run=150, life=50, model_life=40, variant_of="coastal",
         desc="Coastal class, usually on the Duke Point - Tsawwassen run."),
    dict(id="coastal_cel", weather=0.25, name="Coastal Celebration",
         model=lambda: m_coastal(key="coastal_cel"), year=2008, pax=1604, cars=310, kn=21,
         cost=220, run=150, life=50, model_life=40, variant_of="coastal",
         desc="Coastal class, Swartz Bay - Tsawwassen."),
    dict(id="coastal_insp_2010", weather=0.12, name="Coastal Inspiration (Vancouver 2010)",
         model=lambda: m_coastal(True, key="coastal_insp", wrap="inspiration"), year=2008,
         pax=1604, cars=310, kn=21, cost=220, run=150, life=50, model_life=40,
         variant_of="coastal",
         desc="Coastal Inspiration's own Vancouver 2010 wrap: snowboarder and orca panels."),
    dict(id="coastal_cel_2010", weather=0.12, name="Coastal Celebration (Vancouver 2010)",
         model=lambda: m_coastal(True, key="coastal_cel", wrap="celebration"), year=2008,
         pax=1604, cars=310, kn=21, cost=220, run=150, life=50, model_life=40,
         variant_of="coastal",
         desc="Coastal Celebration's Vancouver 2010 wrap: Team Canada and BC coast panels."),
    dict(id="cclass_cow", weather=0.6, name="Queen of Cowichan",
         model=lambda: m_cclass(key="cclass_cow"), year=1976, pax=1466, cars=362, kn=20.5,
         cost=190, run=150, life=50, model_life=10, variant_of="cclass",
         desc="C-class, Horseshoe Bay - Departure Bay."),
    dict(id="cclass_alb", weather=0.6, name="Queen of Alberni",
         model=lambda: m_cclass(key="cclass_alb"), year=1976, pax=1466, cars=362, kn=20.5,
         cost=190, run=150, life=50, model_life=10, variant_of="cclass",
         desc="C-class, Duke Point - Tsawwassen."),
    dict(id="cclass_sur", weather=0.7, name="Queen of Surrey",
         model=lambda: m_cclass(True, key="cclass_sur"), year=1981, pax=1494, cars=322,
         kn=20.5, cost=190, run=150, life=50, model_life=45, variant_of="cclass_ob",
         desc="C-class (Oak Bay type), sister to Queen of Oak Bay."),
    dict(id="salish_eagle", weather=0.15, name="Salish Eagle",
         model=lambda: m_salish(key="salish_eagle", art="eagle"), year=2017, pax=600,
         cars=145, kn=15.5, cost=150, run=90, life=45, model_life=40, variant_of="salish",
         desc="Salish class, dual-fuel LNG. Hull art by Coast Salish artist John Marston "
              "(Stz'uminus First Nation)."),
    dict(id="salish_raven", weather=0.15, name="Salish Raven",
         model=lambda: m_salish(key="salish_raven", art="raven"), year=2017, pax=600,
         cars=145, kn=15.5, cost=150, run=90, life=45, model_life=40, variant_of="salish",
         desc="Salish class, dual-fuel LNG. Hull art by Coast Salish artist Thomas Cannell "
              "(Musqueam)."),
    dict(id="burnaby_nan", weather=0.6, name="Queen of Nanaimo",
         model=lambda: m_burnaby(key="burnaby_nan"), year=1965, pax=1200, cars=192, kn=18,
         cost=160, run=130, life=45, model_life=25, variant_of="burnaby",
         desc="Burnaby class sister."),
    dict(id="burnaby_nw", weather=0.6, name="Queen of New Westminster",
         model=lambda: m_burnaby(key="burnaby_nw"), year=1964, pax=1200, cars=192, kn=18,
         cost=160, run=130, life=45, model_life=25, variant_of="burnaby",
         desc="Built at Victoria Machinery Depot; a near-sister of the Burnaby class."),
    dict(id="intermediate_cum", weather=0.5, name="Queen of Cumberland",
         model=lambda: m_intermediate(key="intermediate_cum"), year=1992, pax=462, cars=100,
         kn=15.5, cost=110, run=80, life=45, model_life=35, variant_of="intermediate",
         desc="Intermediate class, Swartz Bay - Southern Gulf Islands."),
    dict(id="vclass_s_vic", weather=0.55, name="Queen of Victoria",
         model=lambda: m_vclass(True, key="vclass_s_vic"), year=1970, pax=1360, cars=192,
         kn=18, cost=165, run=130, life=40, model_life=30, variant_of="vclass_s",
         desc="V-class after stretching, sister to Queen of Vancouver."),
    dict(id="salish_heron", weather=0.1, name="Salish Heron",
         model=lambda: m_salish(key="salish_heron", art="heron"), year=2022, pax=600,
         cars=145, kn=15.5, cost=150, run=90, life=45, model_life=40, variant_of="salish",
         desc="Fourth Salish class ship, dual-fuel LNG. Hull art by Maynard Johnny Jr."),
    # ---- Victoria Clipper (passenger-only fast catamarans) -----------------
    dict(id="clipper4", weather=0.3, name="Victoria Clipper IV",
         model=lambda: m_clipper(4), year=1993, pax=330, cars=0, kn=28,
         cost=140, run=150, life=30, model_life=30, pax_only=True,
         desc="Clipper Navigation's Seattle - Victoria passenger catamaran (Fjellstrand 40 m)."),
    dict(id="clipper5", weather=0.15, name="Victoria Clipper V",
         model=lambda: m_clipper(5), year=2019, pax=540, cars=0, kn=36,
         cost=170, run=190, life=30, model_life=40, pax_only=True, variant_of="clipper4",
         desc="Fastest of the Clippers (Fjellstrand 52 m, built 2003), Seattle - Victoria."),
]

