"""Generate the terminals GRF source: bc-terminals.nml and
lang/terminals/english.lng from gfx/objects.json (src/make_objects.py)."""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "common"))
from nmlcommon import SPRITESET, write  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

VERSION = 2
HEADER = """\
// BC Ferries terminals NewGRF -- GENERATED by src/make_nml_terminals.py

grf {
    grfid: "TFBT";
    name: string(STR_GRF_NAME);
    desc: string(STR_GRF_DESC);
    version: %d;
    min_compatible_version: 1;
}
""" % VERSION

LANG = """\
##grflangid 0x01
# GENERATED by src/make_nml_terminals.py

STR_GRF_NAME :BC Ferries: Terminals {SILVER}v%d
STR_GRF_DESC :Terminal objects for Tsawwassen, Swartz Bay and the Southern Gulf Islands: buildings, toll plazas, holding lanes, berths, walkways, foot-passenger areas, The Stand at Otter Bay and island forest. Use with BC Ferries: Vessels.
""" % VERSION


TERMINAL_CLASSES = {None: ("BCFT", "STR_OBJ_CLASS_BCF", "BC Ferries: Tsawwassen"),
                    "sb": ("BCFS", "STR_OBJ_CLASS_BCFS", "BC Ferries: Swartz Bay"),
                    "isl": ("BCFI", "STR_OBJ_CLASS_BCFI", "BC Ferries: Gulf Islands")}


def objects_nml(lang, objects=None, path=None, classes=None):
    """Terminal objects (src/make_objects.py): one spriteset per variant and
    view, one sprite layout per tile; chosen by view, then (for objects with
    several variants) the tile's random bits, then the tile's offset."""
    path = path or os.path.join(ROOT, "gfx", "objects.json")
    if not os.path.exists(path):
        return ""
    if objects is None:
        from make_objects import OBJECTS as objects
    classes = classes or TERMINAL_CLASSES
    meta = json.load(open(path))
    out = ["\n/* ==== Objects ==== */\n"]
    for label, sid, text in classes.values():
        lang.append("%s :%s" % (sid, text))
    OBJECTS = objects
    for num, o in enumerate(OBJECTS):        # list position = object ID: append only!
        oid, variants = o["id"], meta[o["id"]]["variants"]
        ground = "GROUNDSPRITE_WATER" if o.get("water") else "GROUNDSPRITE_CONCRETE"
        zext = 8 * (o["height"] + 1)
        view_cases = []
        for view in range(o["views"]):
            var_cases = []
            for vi, vmeta in enumerate(variants):
                v = vmeta[str(view)]
                tag = "%s_%d_v%d" % (oid, vi, view)
                fmt = lambda key: "\n".join("    [%d, %d, %d, %d, %d, %d]" % tuple(e) for e in v[key])  # noqa: E731
                out.append(SPRITESET % dict(name="obj_" + tag, file="obj_" + tag, s8=fmt("8bpp"),
                                            s1=fmt("1x"), s2=fmt("2x"), s4=fmt("4x")))
                cases = []
                for i, (tx, ty) in enumerate(v["tiles"]):
                    lay = "lay_obj_%s_%d" % (tag, i)
                    out.append("spritelayout %s {\n    ground { sprite: %s; }\n"
                               "    building { sprite: ss_obj_%s(%d); xextent: 16; yextent: 16; "
                               "zextent: %d; }\n}\n" % (lay, ground, tag, i, zext))
                    cases.append("    %d: %s;" % (tx + 16 * ty, lay))
                if len(cases) > 1:
                    out.append("switch(FEAT_OBJECTS, SELF, sw_obj_%s, relative_x + 16 * relative_y) {\n"
                               "%s\n    lay_obj_%s_0;\n}\n" % (tag, "\n".join(cases), tag))
                    var_cases.append("    %d: sw_obj_%s;" % (vi, tag))
                else:                                # single tile: use its layout directly
                    var_cases.append("    %d: lay_obj_%s_0;" % (vi, tag))
            if len(variants) > 1:
                out.append("switch(FEAT_OBJECTS, SELF, sw_obj_%s_v%d, random_bits %% %d) {\n%s\n"
                           "    %s\n}\n" % (oid, view, len(variants), "\n".join(var_cases),
                                           var_cases[0].split(": ")[1]))
                view_cases.append("    %d: sw_obj_%s_v%d;" % (view, oid, view))
            else:
                view_cases.append("    %d: %s" % (view, var_cases[0].split(": ")[1]))
        if len(view_cases) > 1:
            out.append("switch(FEAT_OBJECTS, SELF, sw_obj_%s, view) {\n%s\n    %s\n}\n"
                       % (oid, "\n".join(view_cases), view_cases[0].split(": ")[1]))
            top = "sw_obj_%s" % oid
        else:
            top = view_cases[0].split(": ")[1].rstrip(";")
        flags = "bitmask(OBJ_FLAG_ON_WATER, OBJ_FLAG_NOT_ON_LAND)" if o.get("water") else "bitmask()"
        out.append("""item(FEAT_OBJECTS, obj_%(id)s, %(num)d) {
    property {
        class: "%(cls)s";
        classname: string(%(clsname)s);
        name: string(STR_OBJ_%(ID)s);
        climates_available: ALL_CLIMATES;
        size: [%(w)d, %(d)d];
        build_cost_multiplier: %(cost)d;
        remove_cost_multiplier: %(cost)d;
        introduction_date: date(%(year)d, 1, 1);
        object_flags: %(flags)s;
        height: %(height)d;
        num_views: %(views)d;
    }
    graphics {
        default: %(top)s;
    }
}
""" % dict(id=oid, ID=oid.upper(), num=num, top=top,
           cls=classes[o.get("cls")][0], clsname=classes[o.get("cls")][1], w=o["size"][0], d=o["size"][1], cost=o["cost"],
           year=o["year"], height=o["height"], views=o["views"], flags=flags))
        lang.append("STR_OBJ_%s :%s" % (oid.upper(), o["name"]))
    return "".join(out)


def main():
    lang = [LANG]
    out = [HEADER, objects_nml(lang)]
    write(os.path.join(ROOT, "bc-terminals.nml"), out, os.path.join(ROOT, "lang"), lang)
    print("wrote bc-terminals.nml")


if __name__ == "__main__":
    main()
