"""Generate bcferries.nml and lang/english.lng from ships.FLEET + gfx/sprites.json."""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from ships import FLEET  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GRF_VERSION = 5

HEADER = """\
// BC Ferries NewGRF -- GENERATED by src/make_nml.py, do not edit by hand.

grf {
    grfid: "TFBC";
    name: string(STR_GRF_NAME);
    desc: string(STR_GRF_DESC);
    version: %(version)d;
    min_compatible_version: 1;
    param 0 {
        cap_mode {
            type: int;
            name: string(STR_PARAM_CAP);
            desc: string(STR_PARAM_CAP_DESC);
            min_value: 0;
            max_value: 2;
            def_value: 0;
            names: {
                0: string(STR_PARAM_CAP_100);
                1: string(STR_PARAM_CAP_50);
                2: string(STR_PARAM_CAP_25);
            };
        }
    }
}

cargotable {
    PASS, MAIL, GOOD, VEHI
}
"""

ITEM = """
/* ---- %(name)s ---- */
%(spritesets)s
// Wake and bow wave only while under way
switch(FEAT_SHIPS, SELF, sw_gfx_%(id)s, current_speed) {
    0..3: ss_%(id)s;
    ss_%(id)s_mv;
}

// Vehicle deck: FIRS-style VEHI cargo counts one per car space, other
// freight gets two units per car space.
switch(FEAT_SHIPS, SELF, sw_cap_%(id)s_freight, cargo_type_in_veh) {
    VEHI: return max(1, %(cars)d >> cap_mode);
    return max(1, %(cars2)d >> cap_mode);
}
switch(FEAT_SHIPS, SELF, sw_cap_%(id)s, cargo_classes & bitmask(CC_PASSENGERS)) {
    0: sw_cap_%(id)s_freight;
    return max(1, %(pax)d >> cap_mode);
}

%(smoke_sw)sitem(FEAT_SHIPS, %(id)s, %(num)d) {
    property {
        name: string(STR_NAME_%(ID)s);
        climates_available: bitmask(CLIMATE_TEMPERATE, CLIMATE_ARCTIC, CLIMATE_TROPICAL);
        introduction_date: date(%(year)d, 3, 1);
        model_life: %(model_life)d;
        vehicle_life: %(life)d;
        reliability_decay: %(decay)d;
        cost_factor: %(cost)d;
        running_cost_factor: %(run)d;
        sprite_id: SPRITE_ID_NEW_SHIP;
        speed: %(kmh).1f km/h;
        default_cargo_type: PASS;
        cargo_capacity: %(pax)d;
%(refit)s
        refit_cost: 10;
        loading_speed: %(loading)d;
        sound_effect: SOUND_DEPARTURE_FERRY;%(variant)s%(smoke_prop)s
    }
    graphics {
        cargo_capacity: sw_cap_%(id)s;
        purchase_cargo_capacity: sw_cap_%(id)s;
        additional_text: return string(STR_DESC_%(ID)s);
%(smoke_cb)s        purchase: ss_%(id)s;
        default: sw_gfx_%(id)s;
    }
}
"""

LANG_HEADER = """\
##grflangid 0x01
# GENERATED by src/make_nml.py

STR_GRF_NAME        :BC Ferries, MV Coho & Victoria Clipper {SILVER}v%(version)d
STR_GRF_DESC        :Ferries of British Columbia: BC Ferries' Spirit, Coastal, C-class, Salish, Island and minor-route classes, plus Black Ball's MV Coho and the Victoria Clipper.{}{}Passenger ships with a refittable vehicle deck. Includes 32bpp sprites up to 4x zoom. Works with OpenTTD 13+ and JGR's Patch Pack.
STR_PARAM_CAP       :Capacity scale
STR_PARAM_CAP_DESC  :Real ferries carry thousands of passengers. Scale capacities down for a more conventional OpenTTD balance.
STR_PARAM_CAP_100   :Realistic (100%%)
STR_PARAM_CAP_50    :Half (50%%)
STR_PARAM_CAP_25    :Quarter (25%%)
"""


REFIT_FERRY = """        refittable_cargo_classes: bitmask(CC_PASSENGERS, CC_MAIL, CC_EXPRESS, CC_PIECE_GOODS,
                                          CC_ARMOURED, CC_REFRIGERATED);
        non_refittable_cargo_classes: bitmask(CC_LIQUID, CC_BULK);
        cargo_allow_refit: [VEHI];"""
# passenger-only boats: passengers, or mail (pax / 20 bags)
REFIT_PAX = """        refittable_cargo_classes: bitmask(CC_PASSENGERS, CC_MAIL);
        non_refittable_cargo_classes: bitmask(CC_LIQUID, CC_BULK, CC_PIECE_GOODS);"""

# LNG / hybrid ships puff less (random "electric" model); diesels puff steadily.
LIGHT_SMOKE = {"salish", "salish_eagle", "salish_raven", "salish_heron", "island",
               "spirit_lng"}


def smoke_switches(ident, pts_by_dir):
    """Exhaust smoke at the real stack outlets: one switch per direction
    storing create_effect() offsets in temp registers 0x100+."""
    if not pts_by_dir or not pts_by_dir[0]:
        return ""
    out = []
    for d, pts in enumerate(pts_by_dir):
        stores = ", ".join("STORE_TEMP(create_effect(EFFECT_SPRITE_DIESEL, %d, %d, %d), 0x%X)"
                           % (x, y, z, 0x100 + i) for i, (x, y, z) in enumerate(pts))
        out.append("switch(FEAT_SHIPS, SELF, sw_fx_%s_%d, [%s]) {\n"
                   "    return CB_RESULT_CREATE_EFFECT_CENTER | CB_RESULT_CREATE_EFFECT_NO_ROTATION | %d;\n}\n"
                   % (ident, d, stores, len(pts)))
    out.append("switch(FEAT_SHIPS, SELF, sw_fx_%s, direction) {\n%s    sw_fx_%s_0;\n}\n\n"
               % (ident, "".join("    %d: sw_fx_%s_%d;\n" % (d, ident, d) for d in range(8)),
                  ident))
    return "".join(out)


def reliability_decay(s):
    """How fast reliability falls between services. OpenTTD's own ships use
    5 (the hovercraft 10); older classes wear a little faster, the PacifiCat
    like the hovercraft, and the cardboard Pirate Pak fastest of all."""
    if s["id"] == "piratepak":
        return 20
    if s["id"] == "pacificat":
        return 10
    return 7 if s["year"] < 1985 else 5


SPRITESET = """spriteset(ss_%(name)s, "gfx/%(file)s.png") {
%(s8)s
}
alternative_sprites(ss_%(name)s, ZOOM_LEVEL_NORMAL, BIT_DEPTH_32BPP, "gfx/%(file)s_1x.png") {
%(s1)s
}
alternative_sprites(ss_%(name)s, ZOOM_LEVEL_IN_2X, BIT_DEPTH_32BPP, "gfx/%(file)s_2x.png") {
%(s2)s
}
alternative_sprites(ss_%(name)s, ZOOM_LEVEL_IN_4X, BIT_DEPTH_32BPP, "gfx/%(file)s_4x.png") {
%(s4)s
}
"""


def main():
    meta = json.load(open(os.path.join(ROOT, "gfx", "sprites.json")))
    out = [HEADER % {"version": GRF_VERSION}]
    lang = [LANG_HEADER % {"version": GRF_VERSION}]
    for num, s in enumerate(FLEET):          # list position = engine ID: append only!
        def fmt(state, key):
            return "\n".join("    [%d, %d, %d, %d, %d, %d]" % tuple(e)
                             for e in meta[s["id"]][state][key])
        spritesets = "".join(SPRITESET % dict(
            name=s["id"] + suffix, file=s["id"] + suffix, s8=fmt(state, "8bpp"),
            s1=fmt(state, "1x"), s2=fmt(state, "2x"), s4=fmt(state, "4x"))
            for state, suffix in (("still", ""), ("moving", "_mv")))
        variant = ""
        if s.get("variant_of"):
            variant = "\n        variant_group: %s;" % s["variant_of"]
        out.append(ITEM % dict(
            s, ID=s["id"].upper(), num=num, spritesets=spritesets,
            refit=REFIT_PAX if s.get("pax_only") else REFIT_FERRY,
            decay=reliability_decay(s),
            smoke_sw=smoke_switches(s["id"], meta[s["id"]].get("smoke")),
            smoke_prop=("\n        effect_spawn_model: %s;" % (
                "EFFECT_SPAWN_MODEL_ELECTRIC" if s["id"] in LIGHT_SMOKE
                else "EFFECT_SPAWN_MODEL_STEAM")) if meta[s["id"]].get("smoke", [[]])[0] else "",
            smoke_cb=("        create_effect: sw_fx_%s;\n" % s["id"])
            if meta[s["id"]].get("smoke", [[]])[0] else "",
            cars=s["cars"] if not s.get("pax_only") else 10,
            cars2=s["cars"] * 2 if not s.get("pax_only") else max(10, s["pax"] // 20),
            kmh=s["kn"] * 1.852, loading=max(10, s["pax"] // 20), variant=variant))
        ID = s["id"].upper()
        lang.append("STR_NAME_%s :%s" % (ID, s["name"]))
        if s.get("pax_only"):
            lang.append("STR_DESC_%s :%s{}{BLACK}Passengers only. Real-world: {GOLD}%d{BLACK} "
                        "passengers, %s knots" % (ID, s["desc"], s["pax"], "%g" % s["kn"]))
        elif s.get("joke"):
            lang.append("STR_DESC_%s :%s" % (ID, s["desc"]))
        else:
            lang.append("STR_DESC_%s :%s{}{BLACK}Real-world: {GOLD}%d{BLACK} passengers, "
                        "{GOLD}%d{BLACK} vehicles, %s knots"
                        % (ID, s["desc"], s["pax"], s["cars"], ("%g" % s["kn"])))
    with open(os.path.join(ROOT, "bcferries.nml"), "w") as f:
        f.write("\n".join(out))
    os.makedirs(os.path.join(ROOT, "lang"), exist_ok=True)
    with open(os.path.join(ROOT, "lang", "english.lng"), "w") as f:
        f.write("\n".join(lang) + "\n")
    print("wrote bcferries.nml (%d ships)" % len(FLEET))


if __name__ == "__main__":
    main()
